name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RELEASE_PLZ_LOG: DEBUG release-plz
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: Release-plz
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'BrickUIApp' }}
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Install GitHub CLI (Local only)
        if: ${{ env.ACT }}
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.RELEASE_TOKEN }}
          persist-credentials: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Force Sync Tags
        run: |
          git tag -l | xargs git tag -d
          git fetch --tags --force

      - name: Run release-plz
        uses: release-plz/action@v0.5.139
        with:
          manifest_path: ./src-tauri/Cargo.toml
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}